export const tools = [
  {name: 'move', id: 0, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_move.svg/32px-Mode_move.svg.png'},
  {name: 'point', id: 1, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_point.svg/32px-Mode_point.svg.png'},
  {name: 'join', id: 2, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_join.svg/32px-Mode_join.svg.png'},
  {name: 'parallel', id: 3, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_parallel.svg/32px-Mode_parallel.svg.png'},
  {name: 'orthogonal', id: 4, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_orthogonal.svg/32px-Mode_orthogonal.svg.png'},
  {name: 'intersect', id: 5, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_intersect.svg/32px-Mode_intersect.svg.png'},
  {name: 'delete', id: 6, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_delete.svg/32px-Mode_delete.svg.png'},
  {name: 'vector', id: 7, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_vector.svg/32px-Mode_vector.svg.png'},
  {name: 'line_bisector', id: 8, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_linebisector.svg/32px-Mode_linebisector.svg.png'},
  {name: 'angular_bisector', id: 9, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_angularbisector.svg/32px-Mode_angularbisector.svg.png'},
  {name: 'circle_two_points', id: 10, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_circle2.svg/32px-Mode_circle2.svg.png'},
  {name: 'circle_three_points', id: 11, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_circle3.svg/32px-Mode_circle3.svg.png'},
  {name: 'conic_five_points', id: 12, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_conic5.svg/32px-Mode_conic5.svg.png'},
  {name: 'tangents', id: 13, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_tangent.svg/32px-Mode_tangent.svg.png'},
  {name: 'relation', id: 14, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_relation.svg/32px-Mode_relation.svg.png'},
  {name: 'segment', id: 15, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_segment.svg/32px-Mode_segment.svg.png'},
  {name: 'polygon', id: 16, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_polygon.svg/32px-Mode_polygon.svg.png'},
  {name: 'text', id: 17, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_text.svg/32px-Mode_text.svg.png'},
  {name: 'ray', id: 18, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_ray.svg/32px-Mode_ray.svg.png'},
  {name: 'midpoint', id: 19, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_midpoint.svg/32px-Mode_midpoint.svg.png'},
  {name: 'circle_arc_three_points', id: 20, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_circlearc3.svg/32px-Mode_circlearc3.svg.png'},
  {name: 'circle_sector_three_points', id: 21, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_circlesector3.svg/32px-Mode_circlesector3.svg.png'},
  {name: 'circumcircle_arc_three_points', id: 22, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_circumcirclearc3.svg/32px-Mode_circumcirclearc3.svg.png'},
  {name: 'circumcircle_sector_three_points', id: 23, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_circumcirclesector3.svg/32px-Mode_circumcirclesector3.svg.png'},
  {name: 'semicircle', id: 24, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_semicircle.svg/32px-Mode_semicircle.svg.png'},
  {name: 'slider', id: 25, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_slider.svg/32px-Mode_slider.svg.png'},
  {name: 'image', id: 26, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_image.svg/32px-Mode_image.svg.png'},
  {name: 'show_hide_object', id: 27, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_showhideobject.svg/32px-Mode_showhideobject.svg.png'},
  {name: 'show_hide_label', id: 28, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_showhidelabel.svg/32px-Mode_showhidelabel.svg.png'},
  {name: 'mirror_at_point', id: 29, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_mirroratpoint.svg/32px-Mode_mirroratpoint.svg.png'},
  {name: 'mirror_at_line', id: 30, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_mirroratline.svg/32px-Mode_mirroratline.svg.png'},
  {name: 'translate_by_vector', id: 31, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_translatebyvector.svg/32px-Mode_translatebyvector.svg.png'},
  {name: 'rotate_by_angle', id: 32, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_rotatebyangle.svg/32px-Mode_rotatebyangle.svg.png'},
  {name: 'dilate_from_point', id: 33, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_dilatefrompoint.svg/32px-Mode_dilatefrompoint.svg.png'},
  {name: 'circle_point_radius', id: 34, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_circlepointradius.svg/32px-Mode_circlepointradius.svg.png'},
  {name: 'copy_visual_style', id: 35, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_copyvisualstyle.svg/32px-Mode_copyvisualstyle.svg.png'},
  {name: 'angle', id: 36, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_angle.svg/32px-Mode_angle.svg.png'},
  {name: 'vector_from_point', id: 37, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_vectorfrompoint.svg/32px-Mode_vectorfrompoint.svg.png'},
  {name: 'distance', id: 38, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_distance.svg/32px-Mode_distance.svg.png'},
  {name: 'move_rotate', id: 39, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_moverotate.svg/32px-Mode_moverotate.svg.png'},
  {name: 'translateview', id: 40, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_translateview.svg/32px-Mode_translateview.svg.png'},
  {name: 'zoom_in', id: 41, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_zoomin.svg/32px-Mode_zoomin.svg.png'},
  {name: 'zoom_out', id: 42, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_zoomout.svg/32px-Mode_zoomout.svg.png'},
  {name: 'selection_listener', id: 43, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_/32px-Mode_.png'},
  {name: 'polar_diameter', id: 44, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_polardiameter.svg/32px-Mode_polardiameter.svg.png'},
  {name: 'segment_fixed', id: 45, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_segmentfixed.svg/32px-Mode_segmentfixed.svg.png'},
  {name: 'angle_fixed', id: 46, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_anglefixed.svg/32px-Mode_anglefixed.svg.png'},
  {name: 'locus', id: 47, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_locus.svg/32px-Mode_locus.svg.png'},
  {name: 'macro', id: 48, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_tool.svg/32px-Mode_tool.svg.png'},
  {name: 'area', id: 49, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_area.svg/32px-Mode_area.svg.png'},
  {name: 'slope', id: 50, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_slope.svg/32px-Mode_slope.svg.png'},
  {name: 'regular_polygon', id: 51, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_regularpolygon.svg/32px-Mode_regularpolygon.svg.png'},
  {name: 'show_hide_checkbox', id: 52, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_showcheckbox.svg/32px-Mode_showcheckbox.svg.png'},
  {name: 'compasses', id: 53, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_compasses.svg/32px-Mode_compasses.svg.png'},
  {name: 'mirror_at_circle', id: 54, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_mirroratcircle.svg/32px-Mode_mirroratcircle.svg.png'},
  {name: 'ellipse_three_points', id: 55, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_ellipse3.svg/32px-Mode_ellipse3.svg.png'},
  {name: 'hyperbola_three_points', id: 56, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_hyperbola3.svg/32px-Mode_hyperbola3.svg.png'},
  {name: 'parabola', id: 57, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_parabola.svg/32px-Mode_parabola.svg.png'},
  {name: 'fitline', id: 58, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_fitline.svg/32px-Mode_fitline.svg.png'},
  {name: 'record_to_spreadsheet', id: 59, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_recordtospreadsheet.svg/32px-Mode_recordtospreadsheet.svg.png'},
  {name: 'button_action', id: 60, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_buttonaction.svg/32px-Mode_buttonaction.svg.png'},
  {name: 'textfield_action', id: 61, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_textfieldaction.svg/32px-Mode_textfieldaction.svg.png'},
  {name: 'pen', id: 62, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_pen.svg/32px-Mode_pen.svg.png'},
  {name: 'rigid Polygon', id: 64, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_rigidpolygon.svg/32px-Mode_rigidpolygon.svg.png'},
  {name: 'polyline', id: 65, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_polyline.svg/32px-Mode_polyline.svg.png'},
  {name: 'probability Calculator', id: 66, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_probabilitycalculator.svg/32px-Mode_probabilitycalculator.svg.png'},
  {name: 'attach / Detach', id: 67, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_attachdetachpoint.svg/32px-Mode_attachdetachpoint.svg.png'},
  {name: 'function Inspector', id: 68, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_functioninspector.svg/32px-Mode_functioninspector.svg.png'},
  {name: 'intersect Two Surfaces', id: 69},
  {name: 'vector Polygon', id: 70, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_vectorpolygon.svg/32px-Mode_vectorpolygon.svg.png'},
  {name: 'create List', id: 71, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_createlist.svg/32px-Mode_createlist.svg.png'},
  {name: 'complex Number', id: 72, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_complexnumber.svg/32px-Mode_complexnumber.svg.png'},
  {name: 'point on object', id: 501, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_pointonobject.svg/32px-Mode_pointonobject.svg.png'},
  {name: 'mode_spreadsheet_create_list', id: 2001, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_createlist.svg/32px-Mode_createlist.svg.png'},
  {name: 'mode_spreadsheet_create_matrix', id: 2002, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_creatematrix.svg/32px-Mode_creatematrix.svg.png'},
  {name: 'mode_spreadsheet_create_listofpoints', id: 2003, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_createlistofpoints.svg/32px-Mode_createlistofpoints.svg.png'},
  {name: 'mode_spreadsheet_create_tabletext', id: 2004, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_createtable.svg/32px-Mode_createtable.svg.png'},
  {name: 'mode_spreadsheet_create_polyline', id: 2005, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_createpolyline.svg/32px-Mode_createpolyline.svg.png'},
  {name: 'mode_spreadsheet_onevarstats', id: 2020, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_onevarstats.svg/32px-Mode_onevarstats.svg.png'},
  {name: 'mode_spreadsheet_twovarstats', id: 2021, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_twovarstats.svg/32px-Mode_twovarstats.svg.png'},
  {name: 'mode_spreadsheet_multivarstats', id: 2022, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_multivarstats.svg/32px-Mode_multivarstats.svg.png'},
  {name: 'mode_spreadsheet_sort', id: 2030, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_/32px-Mode_.png'},
  {name: 'mode_spreadsheet_sort_az', id: 2031, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_/32px-Mode_.png'},
  {name: 'mode_spreadsheet_sort_za', id: 2032, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_/32px-Mode_.png'},
  {name: 'mode_spreadsheet_sum', id: 2040, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_sumcells.svg/32px-Mode_sumcells.svg.png'},
  {name: 'mode_spreadsheet_average', id: 2041, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_meancells.svg/32px-Mode_meancells.svg.png'},
  {name: 'mode_spreadsheet_count', id: 2042, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_countcells.svg/32px-Mode_countcells.svg.png'},
  {name: 'mode_spreadsheet_min', id: 2043, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_mincells.svg/32px-Mode_mincells.svg.png'},
  {name: 'mode_spreadsheet_max', id: 2044, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_maxcells.svg/32px-Mode_maxcells.svg.png'},
  {name: 'freehand Mode', id: 73, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_freehandshape.svg/32px-Mode_freehandshape.svg.png'},
  {name: 'view_in_front_of', id: 502, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_viewinfrontof.svg/32px-Mode_viewinfrontof.svg.png'},
  {name: 'plane_three_points', id: 510, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_planethreepoint.svg/32px-Mode_planethreepoint.svg.png'},
  {name: 'plane_point_line', id: 511, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_plane.svg/32px-Mode_plane.svg.png'},
  {name: 'orthogonal_plane', id: 512, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_orthogonalplane.svg/32px-Mode_orthogonalplane.svg.png'},
  {name: 'parallel_plane', id: 513, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_parallelplane.svg/32px-Mode_parallelplane.svg.png'},
  {name: 'perpendicular line (3D)', id: 514, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_orthogonalthreed.svg/32px-Mode_orthogonalthreed.svg.png'},
  {name: 'sphere_point_radius', id: 520, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_spherepointradius.svg/32px-Mode_spherepointradius.svg.png'},
  {name: 'sphere_two_points', id: 521, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_sphere2.svg/32px-Mode_sphere2.svg.png'},
  {name: 'cone given by two points and radius', id: 522, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_cone.svg/32px-Mode_cone.svg.png'},
  {name: 'cylinder given by two points and radius', id: 523, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_cylinder.svg/32px-Mode_cylinder.svg.png'},
  {name: 'prism', id: 531, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_prism.svg/32px-Mode_prism.svg.png'},
  {name: 'extrude to Prism or Cylinder', id: 532, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_extrusion.svg/32px-Mode_extrusion.svg.png'},
  {name: 'pyramid', id: 533, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_pyramid.svg/32px-Mode_pyramid.svg.png'},
  {name: 'extrude to Pyramid or Cone', id: 534, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_conify.svg/32px-Mode_conify.svg.png'},
  {name: 'net', id: 535, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_net.svg/32px-Mode_net.svg.png'},
  {name: 'cube', id: 536, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_cube.svg/32px-Mode_cube.svg.png'},
  {name: 'tetrahedron', id: 537, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_tetrahedron.svg/32px-Mode_tetrahedron.svg.png'},
  {name: 'rotate View', id: 540, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_rotateview.svg/32px-Mode_rotateview.svg.png'},
  {name: 'circle Point Radius Direction', id: 550, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_circlepointradiusdirection.svg/32px-Mode_circlepointradiusdirection.svg.png'},
  {name: 'circle Axis Point', id: 551, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_circleaxispoint.svg/32px-Mode_circleaxispoint.svg.png'},
  {name: 'volume', id: 560, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_volume.svg/32px-Mode_volume.svg.png'},
  {name: 'rotate around Line', id: 570, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_rotatearoundline.svg/32px-Mode_rotatearoundline.svg.png'},
  {name: 'mirror at Plane', id: 571, img: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_/32px-Mode_.png'},
]
