export const stdTools = [
  {id: 0, name: 'move', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_move.svg/32px-Mode_move.svg.png'},
  {id: 1, name: 'point', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_point.svg/32px-Mode_point.svg.png'},
  {id: 2, name: 'join', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_join.svg/32px-Mode_join.svg.png'},
  {id: 3, name: 'parallel', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_parallel.svg/32px-Mode_parallel.svg.png'},
  {id: 4, name: 'orthogonal', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_orthogonal.svg/32px-Mode_orthogonal.svg.png'},
  {id: 5, name: 'intersect', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_intersect.svg/32px-Mode_intersect.svg.png'},
  {id: 6, name: 'delete', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_delete.svg/32px-Mode_delete.svg.png'},
  {id: 7, name: 'vector', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_vector.svg/32px-Mode_vector.svg.png'},
  {id: 8, name: 'line_bisector', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_linebisector.svg/32px-Mode_linebisector.svg.png'},
  {id: 9, name: 'angular_bisector', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_angularbisector.svg/32px-Mode_angularbisector.svg.png'},
  {id: 10, name: 'circle_two_points', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_circle2.svg/32px-Mode_circle2.svg.png'},
  {id: 11, name: 'circle_three_points', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_circle3.svg/32px-Mode_circle3.svg.png'},
  {id: 12, name: 'conic_five_points', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_conic5.svg/32px-Mode_conic5.svg.png'},
  {id: 13, name: 'tangents', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_tangent.svg/32px-Mode_tangent.svg.png'},
  {id: 14, name: 'relation', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_relation.svg/32px-Mode_relation.svg.png'},
  {id: 15, name: 'segment', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_segment.svg/32px-Mode_segment.svg.png'},
  {id: 16, name: 'polygon', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_polygon.svg/32px-Mode_polygon.svg.png'},
  {id: 17, name: 'text', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_text.svg/32px-Mode_text.svg.png'},
  {id: 18, name: 'ray', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_ray.svg/32px-Mode_ray.svg.png'},
  {id: 19, name: 'midpoint', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_midpoint.svg/32px-Mode_midpoint.svg.png'},
  {id: 20, name: 'circle_arc_three_points', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_circlearc3.svg/32px-Mode_circlearc3.svg.png'},
  {id: 21, name: 'circle_sector_three_points', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_circlesector3.svg/32px-Mode_circlesector3.svg.png'},
  {id: 22, name: 'circumcircle_arc_three_points', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_circumcirclearc3.svg/32px-Mode_circumcirclearc3.svg.png'},
  {id: 23, name: 'circumcircle_sector_three_points', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_circumcirclesector3.svg/32px-Mode_circumcirclesector3.svg.png'},
  {id: 24, name: 'semicircle', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_semicircle.svg/32px-Mode_semicircle.svg.png'},
  {id: 25, name: 'slider', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_slider.svg/32px-Mode_slider.svg.png'},
  {id: 26, name: 'image', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_image.svg/32px-Mode_image.svg.png'},
  {id: 27, name: 'show_hide_object', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_showhideobject.svg/32px-Mode_showhideobject.svg.png'},
  {id: 28, name: 'show_hide_label', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_showhidelabel.svg/32px-Mode_showhidelabel.svg.png'},
  {id: 29, name: 'mirror_at_point', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_mirroratpoint.svg/32px-Mode_mirroratpoint.svg.png'},
  {id: 30, name: 'mirror_at_line', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_mirroratline.svg/32px-Mode_mirroratline.svg.png'},
  {id: 31, name: 'translate_by_vector', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_translatebyvector.svg/32px-Mode_translatebyvector.svg.png'},
  {id: 32, name: 'rotate_by_angle', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_rotatebyangle.svg/32px-Mode_rotatebyangle.svg.png'},
  {id: 33, name: 'dilate_from_point', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_dilatefrompoint.svg/32px-Mode_dilatefrompoint.svg.png'},
  {id: 34, name: 'circle_point_radius', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_circlepointradius.svg/32px-Mode_circlepointradius.svg.png'},
  {id: 35, name: 'copy_visual_style', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_copyvisualstyle.svg/32px-Mode_copyvisualstyle.svg.png'},
  {id: 36, name: 'angle', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_angle.svg/32px-Mode_angle.svg.png'},
  {id: 37, name: 'vector_from_point', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_vectorfrompoint.svg/32px-Mode_vectorfrompoint.svg.png'},
  {id: 38, name: 'distance', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_distance.svg/32px-Mode_distance.svg.png'},
  {id: 39, name: 'move_rotate', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_moverotate.svg/32px-Mode_moverotate.svg.png'},
  {id: 40, name: 'translateview', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_translateview.svg/32px-Mode_translateview.svg.png'},
  {id: 41, name: 'zoom_in', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_zoomin.svg/32px-Mode_zoomin.svg.png'},
  {id: 42, name: 'zoom_out', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_zoomout.svg/32px-Mode_zoomout.svg.png'},
  {id: 43, name: 'selection_listener', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_/32px-Mode_.png'},
  {id: 44, name: 'polar_diameter', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_polardiameter.svg/32px-Mode_polardiameter.svg.png'},
  {id: 45, name: 'segment_fixed', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_segmentfixed.svg/32px-Mode_segmentfixed.svg.png'},
  {id: 46, name: 'angle_fixed', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_anglefixed.svg/32px-Mode_anglefixed.svg.png'},
  {id: 47, name: 'locus', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_locus.svg/32px-Mode_locus.svg.png'},
  {id: 48, name: 'macro', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_tool.svg/32px-Mode_tool.svg.png'},
  {id: 49, name: 'area', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_area.svg/32px-Mode_area.svg.png'},
  {id: 50, name: 'slope', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_slope.svg/32px-Mode_slope.svg.png'},
  {id: 51, name: 'regular_polygon', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_regularpolygon.svg/32px-Mode_regularpolygon.svg.png'},
  {id: 52, name: 'show_hide_checkbox', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_showcheckbox.svg/32px-Mode_showcheckbox.svg.png'},
  {id: 53, name: 'compasses', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_compasses.svg/32px-Mode_compasses.svg.png'},
  {id: 54, name: 'mirror_at_circle', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_mirroratcircle.svg/32px-Mode_mirroratcircle.svg.png'},
  {id: 55, name: 'ellipse_three_points', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_ellipse3.svg/32px-Mode_ellipse3.svg.png'},
  {id: 56, name: 'hyperbola_three_points', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_hyperbola3.svg/32px-Mode_hyperbola3.svg.png'},
  {id: 57, name: 'parabola', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_parabola.svg/32px-Mode_parabola.svg.png'},
  {id: 58, name: 'fitline', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_fitline.svg/32px-Mode_fitline.svg.png'},
  {id: 59, name: 'record_to_spreadsheet', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_recordtospreadsheet.svg/32px-Mode_recordtospreadsheet.svg.png'},
  {id: 60, name: 'button_action', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_buttonaction.svg/32px-Mode_buttonaction.svg.png'},
  {id: 61, name: 'textfield_action', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_textfieldaction.svg/32px-Mode_textfieldaction.svg.png'},
  {id: 62, name: 'pen', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_pen.svg/32px-Mode_pen.svg.png'},
  {id: 64, name: 'rigid Polygon', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_rigidpolygon.svg/32px-Mode_rigidpolygon.svg.png'},
  {id: 65, name: 'polyline', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_polyline.svg/32px-Mode_polyline.svg.png'},
  {id: 66, name: 'probability Calculator', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_probabilitycalculator.svg/32px-Mode_probabilitycalculator.svg.png'},
  {id: 67, name: 'attach / Detach', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_attachdetachpoint.svg/32px-Mode_attachdetachpoint.svg.png'},
  {id: 68, name: 'function Inspector', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_functioninspector.svg/32px-Mode_functioninspector.svg.png'},
  {id: 69, name: 'intersect Two Surfaces' },
  {id: 70, name: 'vector Polygon', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_vectorpolygon.svg/32px-Mode_vectorpolygon.svg.png'},
  {id: 71, name: 'create List', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_createlist.svg/32px-Mode_createlist.svg.png'},
  {id: 72, name: 'complex Number', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_complexnumber.svg/32px-Mode_complexnumber.svg.png'},
  {id: 501, name: 'point on object', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_pointonobject.svg/32px-Mode_pointonobject.svg.png'},
  {id: 2001, name: 'mode_spreadsheet_create_list', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_createlist.svg/32px-Mode_createlist.svg.png'},
  {id: 2002, name: 'mode_spreadsheet_create_matrix', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_creatematrix.svg/32px-Mode_creatematrix.svg.png'},
  {id: 2003, name: 'mode_spreadsheet_create_listofpoints', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_createlistofpoints.svg/32px-Mode_createlistofpoints.svg.png'},
  {id: 2004, name: 'mode_spreadsheet_create_tabletext', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_createtable.svg/32px-Mode_createtable.svg.png'},
  {id: 2005, name: 'mode_spreadsheet_create_polyline', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_createpolyline.svg/32px-Mode_createpolyline.svg.png'},
  {id: 2020, name: 'mode_spreadsheet_onevarstats', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_onevarstats.svg/32px-Mode_onevarstats.svg.png'},
  {id: 2021, name: 'mode_spreadsheet_twovarstats', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_twovarstats.svg/32px-Mode_twovarstats.svg.png'},
  {id: 2022, name: 'mode_spreadsheet_multivarstats', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_multivarstats.svg/32px-Mode_multivarstats.svg.png'},
  {id: 2030, name: 'mode_spreadsheet_sort', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_/32px-Mode_.png'},
  {id: 2031, name: 'mode_spreadsheet_sort_az', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_/32px-Mode_.png'},
  {id: 2032, name: 'mode_spreadsheet_sort_za', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_/32px-Mode_.png'},
  {id: 2040, name: 'mode_spreadsheet_sum', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_sumcells.svg/32px-Mode_sumcells.svg.png'},
  {id: 2041, name: 'mode_spreadsheet_average', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_meancells.svg/32px-Mode_meancells.svg.png'},
  {id: 2042, name: 'mode_spreadsheet_count', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_countcells.svg/32px-Mode_countcells.svg.png'},
  {id: 2043, name: 'mode_spreadsheet_min', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_mincells.svg/32px-Mode_mincells.svg.png'},
  {id: 2044, name: 'mode_spreadsheet_max', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_maxcells.svg/32px-Mode_maxcells.svg.png'},
  {id: 73, name: 'freehand Mode', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_freehandshape.svg/32px-Mode_freehandshape.svg.png'},
  {id: 502, name: 'view_in_front_of', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_viewinfrontof.svg/32px-Mode_viewinfrontof.svg.png'},
  {id: 510, name: 'plane_three_points', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_planethreepoint.svg/32px-Mode_planethreepoint.svg.png'},
  {id: 511, name: 'plane_point_line', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_plane.svg/32px-Mode_plane.svg.png'},
  {id: 512, name: 'orthogonal_plane', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_orthogonalplane.svg/32px-Mode_orthogonalplane.svg.png'},
  {id: 513, name: 'parallel_plane', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_parallelplane.svg/32px-Mode_parallelplane.svg.png'},
  {id: 514, name: 'perpendicular line (3D)', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_orthogonalthreed.svg/32px-Mode_orthogonalthreed.svg.png'},
  {id: 520, name: 'sphere_point_radius', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_spherepointradius.svg/32px-Mode_spherepointradius.svg.png'},
  {id: 521, name: 'sphere_two_points', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_sphere2.svg/32px-Mode_sphere2.svg.png'},
  {id: 522, name: 'cone given by two points and radius', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_cone.svg/32px-Mode_cone.svg.png'},
  {id: 523, name: 'cylinder given by two points and radius', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_cylinder.svg/32px-Mode_cylinder.svg.png'},
  {id: 531, name: 'prism', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_prism.svg/32px-Mode_prism.svg.png'},
  {id: 532, name: 'extrude to Prism or Cylinder', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_extrusion.svg/32px-Mode_extrusion.svg.png'},
  {id: 533, name: 'pyramid', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_pyramid.svg/32px-Mode_pyramid.svg.png'},
  {id: 534, name: 'extrude to Pyramid or Cone', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_conify.svg/32px-Mode_conify.svg.png'},
  {id: 535, name: 'net', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_net.svg/32px-Mode_net.svg.png'},
  {id: 536, name: 'cube', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_cube.svg/32px-Mode_cube.svg.png'},
  {id: 537, name: 'tetrahedron', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_tetrahedron.svg/32px-Mode_tetrahedron.svg.png'},
  {id: 540, name: 'rotate View', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_rotateview.svg/32px-Mode_rotateview.svg.png'},
  {id: 550, name: 'circle Point Radius Direction', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_circlepointradiusdirection.svg/32px-Mode_circlepointradiusdirection.svg.png'},
  {id: 551, name: 'circle Axis Point', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_circleaxispoint.svg/32px-Mode_circleaxispoint.svg.png'},
  {id: 560, name: 'volume', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_volume.svg/32px-Mode_volume.svg.png'},
  {id: 570, name: 'rotate around Line', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_rotatearoundline.svg/32px-Mode_rotatearoundline.svg.png'},
  {id: 571, name: 'mirror at Plane', src: 'https://wiki.geogebra.org/uploads/thumb/8/83/Mode_/32px-Mode_.png'},
]
